# This file is for local development only
# In production, each service runs as a separate Heroku dyno
# (apart from Postgres which is a Heroku managed database)
version: "3"
services:
  postgres-db:
    image: postgres:10.5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  prisma:
    image: prismagraphql/prisma:1.27
    ports:
      - "4466:4466"
    depends_on:
      - postgres-db
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            migrations: true
            rawAccess: true
  redis:
    image: redis:5.0.3-alpine
    command: redis-server
    ports:
      - "6379:6379"
volumes:
  postgres:
